[project]
name = "kafka-topic-record-picker-python-app"
version = "0.01.00.000"
description = "Kafka Topic Record Picker Python Application"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "confluent-kafka>=2.8.2",
    "pytest>=8.3.5",
]
